### PR TITLE
Update to create a note about VARINT/ vs Compact size potential ambiguity

### PR DESCRIPTION
**Pull request by cculianu**
I only am being a pain about this to avoid headaches for people that are used to the Core line of node software where VARINT exists (internally) and is distinct from Compact size...

### CODE REVIEW

**Comment by thesquaregroot** [comment]
> The "Core" family of software (BCHN, BU, and Flowee) all have an internal "VARINT" format that is distinct from this integer format (this format is referred to as COMPACTSIZE or CompactSize in that lineage of software).

I think the "this" in the parenthetical is potentially ambiguous.  Maybe something like this would be more clear?

> The "Core" family of software (BCHN, BU, and Flowee) all have an internal "VARINT" format that is distinct from this integer format.  In that "Core" lineage of software, COMPACTSIZE or CompactSize is used to refer to the protocol's variable length integer format, while "VarInt" refers specifically to their internal variable length integer format and is not a part of the Bitcoin Cash P2P protocol.

**Comment by cculianu** [comment]
Yes this is good.. let me update.

**Comment by cculianu** [comment]
Ok, updated.

**Comment by joshmg** [comment]
Looks good.  Thanks, @cculianu !

**Pull request merged**
